contexts:
  testnet:
    # module: site
    # portal: wal.app
    package: 0xf99aee9f21493e1590e7e5a9aea6f343a1f381031a04a732724871fc294be799
    staking_object: 0xbe46180321c30aab2f8b3501e24048377287fa708018a5b7c2792b35fe339ee3
    # Below the paths need to be adjusted unless you floowed the CLI instructions and kept the same paths
    general:
      rpc_url: https://fullnode.testnet.sui.io:443
      wallet: ~/.sui/sui_config/client.yaml
      walrus_binary: ~/.local/bin/walrus
      walrus_config: ~/.config/walrus/client_config.yaml
      gas_budget: 500000000
  mainnet: # Ignore mainnet for the hackathon
    # module: site
    # portal: wal.app
    package: 0x26eb7ee8688da02c5f671679524e379f0b837a12f1d1d799f255b7eea260ad27
    staking_object: 0x10b9d30c28448939ce6c4d6c6e0ffce4a7f8a4ada8248bdad09ef8b70e4a3904
    # general:
    #   rpc_url: https://fullnode.mainnet.sui.io:443
    #   wallet: /path/to/.sui/sui_config/client.yaml
    #   walrus_binary: /path/to/walrus
    #   walrus_config: /path/to/mainnet/client_config.yaml
    #   gas_budget: 500000000

default_context: testnet
